spring:
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: root
    password: root
  zipkin:
    rabbitmq:
      queue: zipkin
  application:
    name: provider-demo


server:
  port: 8090

eurekaServer:
  host: localhost
  port: 8080
  user: root
  password: root

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka

